### ISSUE TITLE
Ports Specified Via Prompts

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#103]
Add questions during the initial creation to specify the app ports. It's two steps of manual changes that would be removed.

This would be especially helpful in cases where there may be multiple slush generated projects on a single MarkLogic development environment at once.

**Comment by grtjn** [comment]
Bonus points for auto suggested ports.

Would be a useful addition to Roxy as well, though you cannot ask for user input with Roxy, when run headless from gulp/slush..

**Comment by hunterwilliams** [comment]
This has been merged in. #151 is a continuation on this.
