### ISSUE TITLE
Browser reload/Minification Loop

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#104]
Details
 * Master branch as of c20ca3a5400c7c260e0331ffdadb9858417a53dc
 * Windows 10/Git Bash/Chrome

After editing a html file (like search.html) and if while hosting via gulp I get thrown into a loop where it keeps running less compilation etc. This doesn't happen when I edit a javascript file however the minification runs more times than expected. Afterwards I also have issues with the **serve-dev** command finding the server (which I'm not sure if it's related or not)

![loop](https://cloud.githubusercontent.com/assets/1759942/9102344/3c26ebf0-3c1b-11e5-8fd4-596e1973b8d6.png)

It looks like it could be related to https://github.com/gulpjs/gulp/issues/651  
Wondering if anyone else has had the same issue

**Comment by grtjn** [comment]
It could be caused by the injection of links into index.html. Not sure if that happens in the source of that file, or in a copy (if any). If the watch is also watching the copy, than you get unnecessary loops..

**Comment by hunterwilliams** [comment]
@grtjn I believe that's what is causing it. It happens to me editing pretty much any html file. However it does not happen 100% of the time

**Comment by grtjn** [comment]
Anyone able to reproduce this? Working just fine for me on MacOS, even with BrowserSync..

**Comment by hunterwilliams** [comment]
I think it's honestly been better. Not sure what exactly would have fixed this. Possibly a dependency change.
