### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#105]
As a developer, it'd be helpful to have a landing page with resources/tips/links to ease the development process with the tool. Additionally, it'd be nice so that the page could be edited or reused as a landing page for my application.

**Comment by grtjn** [comment]
The landing page should mostly contain pointers to where to find help. It does not need to list all useful links..

**Comment by grtjn** [comment]
Landing page added in PR #106. Good as is?

**Comment by hunterwilliams** [comment]
Yeah I debated how many links to put..

**Comment by grtjn** [comment]
Closing this
