### ISSUE TITLE
Login Feedback

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#107]
As a user, it's quite confusing when you can't tell if the login failed or just didn't send. This also complicates knowing whether login was a success because you can't tell if it's just being slow or that it failed.

**Comment by hunterwilliams** [comment]
This looks to be because of 
line 4 of user-dir.html

<div class="alert alert-danger" ng-show="user.loginError" ng-cloak>Username and/or Password Incorrect</div>

user is not defined so it will never appear

**Comment by hunterwilliams** [comment]
overall solution: https://github.com/hunterwilliams/slush-marklogic-node/tree/login-feedback

**Comment by ryanjdew** [comment]
Great Hunter. Can you make a pull request?

**Comment by grtjn** [comment]
Looks like this is fixed..
