### ISSUE TITLE
.gitignore dist folder

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#114]
slush-marklogic-node/app/templates/_gitignore

As a developer, I generally do not commit the **dist** folder. It's built every run. Is there any reason to exclude it from the default gitignore file?

**Comment by grtjn** [comment]
+1, and while at it, these qualify as well I'd say:

```
deploy/local.properties
ui/styles/*.css
dist
*.pid
.idea
*.sublime-project
*.sublime-workspace
```

**Comment by paxtonhare** [comment]
Make sure to be careful when putting folders in there. If you only want the top level dist then do:

/dist

In some projects I had a dist folder under some other folders and they also got ignored. oopsie.
