### ISSUE TITLE
Split Login From Project

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#118]
As a developer, I'd like to be able to reuse the login component.

I've done some initial work here: https://github.com/hunterwilliams/slush-marklogic-node/commit/294aec01d69783cbb91544575db126920d3233c0

Is that how it would be envisioned the app would interact with it? Possibly passing an endpoint then a preference of get/post. I know there is some modal work as well, but I assume that would be mostly forward facing.

Edit: 

I know some projects also allow OAuth Login. If the MarkLogic login is to be moved out (logging in via MarkLogic) should we also think about making it more in line with OAuth Authentication or something more generic and having something like this in the app - https://github.com/DaftMonk/fullstack-demo/blob/master/client/components/auth/auth.service.js ? That combined with some other node code allows OAuthLogins which could be useful (or not).

**Comment by grtjn** [comment]
Isolating login stuff into its own module is a good first step. OAuth could be an interesting consideration, but perhaps if would be able to split off login as a bower component, we could have an oauth-login one with the same interface that could replace this one to support OAuth against some configurable server (which doesn't have to be MarkLogic perhaps?)..

@ryanjdew is working on authentication, perhaps talk with him as well..

**Comment by ryanjdew** [comment]
This lines up a lot with what I'm working on. @hunterwilliams, I'll pull in your commit to make sure we're aligned on structure/API. 

As for OAuth, I think that would be good for the future but I feel it is a bit of a distraction from our goal for the upcoming weeks. Maybe we should open a separate ticket specifically for OAuth?

**Comment by grtjn** [comment]
I think this is sufficiently covered for the time being. Feel free to open a new ticket for OAuth, closing this one..
