### ISSUE TITLE
Separate User Service?

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#119]
I know this one was talked about. I'm wondering at what level of detail does this take place? Or would this be a MarkLogic User based service? There are currently items in the app for like profile & email. However I'm not sure if those would be considered standard. 

I know the login service is supposed to be separated but this also sounds like it may either cross functionality or would have a dependency on that.

**Comment by grtjn** [comment]
Maybe user and login service are best bundled together? Makes sense to me at least. Granularity could be useful though. One might want to change login ui, login method, and user management separately in a slush project..

**Comment by grtjn** [comment]
Good enough for the moment..
