### ISSUE TITLE
How bad is running this slush with nodejs 0.10.26?

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#134]
I get some warnings, but can't upgrade to 0.12 because of other demos..

**Comment by grtjn** [comment]
Not noticed issues because of this so far..

**Comment by joemfb** [comment]
node.js v4 is coming very soon; it'll be the first converged release of node.js and io.js. I think we should wait, and upgrade to it once released. More details: https://medium.com/node-js-javascript/4-0-is-the-new-1-0-386597a3436d

**Comment by grtjn** [comment]
We already list 0.12 as dependency. It is me that is behind.. ;-)

**Comment by joemfb** [comment]
node.js v4 just landed: https://nodejs.org/en/blog/release/v4.0.0/. I'll try to test with it when I can.

**Comment by grtjn** [comment]
I'll open a new ticket for node.js v4.

**Comment by grtjn** [comment]
Closing this one. 0.10.x doesn't seem to give much issues, just warnings like these:
```
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
```
