### ISSUE TITLE
Search data only

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#136]
Deploy content uploads dictionary, but dictionary appears in search results. Best to apply collection `data` (or similar) to sample-data, and isolate search options to that.

Also nice to strip away abs path:
```
./ml local mlcp import -input_file_path sample-data -output_uri_replace ".*/sample-data/,\'/sample-data/\'" -output_collections data
```
and:
```
  <search:additional-query>
    <cts:collection-query xmlns:cts="http://marklogic.com/cts">
      <cts:uri>data</cts:uri>
    </cts:collection-query>
  </search:additional-query>
```

**Comment by hunterwilliams** [comment]
Instead could we throw the dictionary in its own collection and do a not query on it?

I feel like it may be a pain to make sure you always add the data collection to any document vs just fixing this one

**Comment by grtjn** [comment]
The not-query that we have now is a bad practice, adding the dictionary to it won't make it better. The collection-query is a much better approach, and very easy to explain. You can also do lots of fun with collections like adding collections like `data/cars` and `data/houses`, and then doing a collection facet with `data/` prefix..

**Comment by grtjn** [comment]
We could add that as a sample facet actually.. :)
