### ISSUE TITLE
Cannot click x to clear search results

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#139]
I think I have reported this before, in demo-cat perhaps? Am I the only one bothered by this?

**Comment by joemfb** [comment]
This is in master?

**Comment by grtjn** [comment]
Yes, there is no dev branch..

**Comment by hunterwilliams** [comment]
This is because of bootstrap css but the fix should probably be in ML Search as it uses the bootstrap class by default and can override the style to fix it. I've created the issue here: https://github.com/joemfb/ml-search-ng/issues/72 and done the pull request on that project as well

**Comment by joemfb** [comment]
The fix has been merged, and will be automatically available as soon as I release v0.2.2 (which satisfies `~0.2.0`). Nothing additional is needed here.

**Comment by grtjn** [comment]
@joemfb what can you tell about release 0.2.2 of ml-search-ng? (bonus points if you use milestones in future.. ;)

**Comment by joemfb** [comment]
I just pushed the release.

**Comment by grtjn** [comment]
0.2.2 works! vanilla slush app gives me this though:

```
bower                                  ECONFLICT Unable to find suitable version for ml-common-ng
```

I think we need to touch bower.json:

```
    "ml-common-ng": "~0.0.6",
    "ml-search-ng": "~0.2.0",
```

**Comment by joemfb** [comment]
I didn't know ml-common-ng was explicitly depend on here. No reason for that, just remove it. It's a dependency of ml-search-ng.

**Comment by grtjn** [comment]
Yep, that seems to work!
