### ISSUE TITLE
Login link not shown as button

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#142]

**Comment by hunterwilliams** [comment]
Any particular button desired? Just the standard blue one?

**Comment by grtjn** [comment]
`btn-primary` makes most sense I think (e.g. bootstrap style). Jen will be reviewing the UI, so she can adjust if she thinks it needs more work..

**Comment by grtjn** [comment]
@jenbreese Something you can look at?

**Comment by jenbreese** [comment]
@grtjn Yes, I will.
