### ISSUE TITLE
Clicking search before login throws TypeError

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#143]
Looks like the 401 is not handled elegantly, and things go wrong in search-ctrl or maybe even deeper down (in ml-search perhaps).

**Comment by joemfb** [comment]
It looks like the interceptor is preventing `$http` from properly rejecting the 401: https://github.com/marklogic/slush-marklogic-node/blob/master/app/templates/ui/app/error/errorInterceptor.service.js#L14

**Comment by grtjn** [comment]
@ryanjdew or @hunterwilliams You two have played with login, right? What do you make of this?

**Comment by grtjn** [comment]
Related to #143?

**Comment by hunterwilliams** [comment]
Good question it actually may be. I've got the fix for the other issue so I'll test this out to see if it still pops.

**Comment by hunterwilliams** [comment]
Can confirm it appears entirely related to #141

**Comment by grtjn** [comment]
Fixed with PR #168 as well..
