### ISSUE TITLE
Cannot add tags (nor friends)

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#144]
on Create page.. tags should work, but broken. Adding friends not available, but details show a friends array?

**Comment by grtjn** [comment]
@jenbreese I fixed add/remove tags, but the tags get placed a little odd. Can you take a quick look at that?

**Comment by jenbreese** [comment]
I'm using Chrome and the latest version of slush. I cannot add tags. I can't type in the input field, @grtjn.

**Comment by grtjn** [comment]
I think my changes haven't been merged yet..

**Comment by grtjn** [comment]
@jenbreese I merged my PR. You should now be able to check the UI on this..

**Comment by jenbreese** [comment]
@grtjn I updated and the tags are still not working for me.

**Comment by grtjn** [comment]
Look inside create.html. It should show `ctrl.addTag` instead of just `addTag` somewhere. The update didn't come through if not..
