### ISSUE TITLE
Logic of adding email(s) on account page not intuitive

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#145]
I think it would be better to show an input fields that get added to the list if non-empty. And instead of Add on right, I'd prefer to see a More underneath..

**Comment by grtjn** [comment]
Additionally, looks between Account and Create not fully consistent I think. Maybe also compare with demo-cat. I think we tweaked it there..

**Comment by grtjn** [comment]
If time permits. Otherwise push to 0.2.1

**Comment by hunterwilliams** [comment]
So change "+" to more aligned underneath textbox on right side? 
Then only add if current box is a nonblank valid email?

**Comment by grtjn** [comment]
Yes on button, though Jen can have a look at the exact presentation as well.

About current box: I would skip the whole newEmail thing, and just append an entry to emails property directly. And filter out empty ones at save..

**Comment by hunterwilliams** [comment]
Either one is pretty easy just your preference

**Comment by grtjn** [comment]
Not personal pref, it is counter-intuitive. I always make the mistake at least once of typing in the email, and then forgetting to click Add. I click Save, which jumps away, making you unaware of your mistake. Not until you not receive notifications, or you go back before you become aware adding email failed. Changing it like I described will prevent the mistake of not clicking Add.

Note: make sure to always show at least one email text box. Or maybe always show one extra, empty one..

**Comment by hunterwilliams** [comment]
Ohhhhh I see your point. Didn't realize that's what happens. Makes a lot more sense now

**Comment by jenbreese** [comment]
Can't the submit button save the added email without the user having to click on the plus? I didn't realize that was how it was working.

**Comment by grtjn** [comment]
That is what i mean. Change the now required Add into a More that only shows more fields. So you only need to click it if you want to type an extra email address..

**Comment by jenbreese** [comment]
Perfect. Thanks @grtjn!
