### ISSUE TITLE
Edit and delete options for slush-marklogic

### ISSUE THREAD

**Issue by Scapadiver** [marklogic/slush-marklogic-node#15]
Great new framework for creating apps in place of app builder.

Is it possible to add the the default configuration the ability edit and delete documents?

Would greatly help in creating sample applications.

**Comment by grtjn** [comment]
Should be pretty straight-forward to reuse the create for edit (like we did in demo-cat). Won't make it in 0.2.0 though..

**Comment by grtjn** [comment]
Still on the list, PR's welcome!

**Comment by grtjn** [comment]
I think we best start with a relatively simple implementation that reuses create page to allow editing as well, alike demo-cat. There is a bit of client-side validation in there as well which is nice to have.

**Comment by grtjn** [comment]
@divino Try to build on top of ui-themes branch. Feel free to open a PR with work in progress, so all can give suggestions along the way..

**Comment by grtjn** [comment]
In meantime we merged ui-themes branch, so you can work against master for this..

**Comment by divino** [comment]
Currently, the details page contains an option to view it either as JSON or XML. We can support both file types if we allow on create to explicitly select what file type to save the data. Right now, we are only saving it as JSON.

**Comment by grtjn** [comment]
Sounds great. I'm thinking of a radio toggle between last input field and submit button. You can also show that at edit, disabled to the format it already has..

**Comment by grtjn** [comment]
Fixed in master..
