### ISSUE TITLE
Redundant images?

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#156]
I see two logo files, and two powered-by ones in ui/images/. I guess we only need one of each..

**Comment by jenbreese** [comment]
We only need this one: images/MarkLogic-Powered-By.png

**Comment by grtjn** [comment]
Ok, logo.* not references. But looks like both powered-by logo's are references. mlu.less points to the other one. And I also see that blues.less, and mlu.less point to a non-existing MarkLogic-White.png? And if I for instance compare with https://mlu.marklogic.com/registration/, then I get even more confused.. :P

@jenbreese Can you take a close look?

**Comment by jenbreese** [comment]
I removed the powered by that we shouldn't be using and I added the missing white logo.

**Comment by jenbreese** [comment]
@grtjn I'm double checking we can use that powered by on a dark background. I might not be able to and it will be removed. I'll update when I know more.

**Comment by grtjn** [comment]
Take your time..

**Comment by grtjn** [comment]
@jenbreese Were you done with checking "powered by on a dark background"? If so, I think we can close this..

**Comment by grtjn** [comment]
Looks like there is no powered-by shown with blues. The black/red one does look ugly with the orange. It converting it to white like the logo on top an idea/option? Not really important..

One other minor thing: mlu.less still points to the wrong powered-by png:

```
    background-image: url(/images/PoweredByMarkLogic.png);
```

It seems to be ignored though, because the correct logo is shown..

**Comment by jenbreese** [comment]
Yes, I removed the powered by in blues. I have a note out to Design if we can have a white powered by but I have not heard back. 

The style in MLU was redundant so I removed it.

**Comment by grtjn** [comment]
Closing this for the time being..
