### ISSUE TITLE
Use Passport For Login

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#175]
As a developer, I would like to be able to swap out logins with more common ones vs necessarily using MarkLogic users.

**Comment by joemfb** [comment]
I've got an implementation using passport here: https://github.com/joemfb/mlpm-registry/blob/master/server.js. It's poorly factored and messy code, but could be a useful starting point.

**Comment by grtjn** [comment]
Assigning this to milestone 0.2.1, nice to have..

**Comment by grtjn** [comment]
Related to #284, and incorporated in PR #285 which supersedes PR #220..

**Comment by grtjn** [comment]
Fixed in master..
