### ISSUE TITLE
Migrate to Node.js v4?

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#188]
Node.js v4 is out. We should run tests to see how compatible the current stack is with that. We should also discuss whether we should really move forward to it soon, or defer till used at large scale?

**Comment by grtjn** [comment]
See also #134

**Comment by hunterwilliams** [comment]
I'm on v4.0.0 and not having any issues with anything that I can tell

**Comment by joemfb** [comment]
Same here, it's all working for me on v4

**Comment by grtjn** [comment]
Sounds like we don't need to take explicit action for this..
