### ISSUE TITLE
Binary Corruption

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#194]
During a slush generation, it appears that the images or zips can be corrupted.

Windows 10
Latest Master Of Slush

Images are not corrupted in the generator locally but get corrupted during slush process

**Comment by grtjn** [comment]
Seen on Mac as well. Could this be a but in one of the npm modules? We are behind on them a bit..

**Comment by grtjn** [comment]
Or could it be more simple? We introduced this replace step, to search for `@sample-app`. Could that be messing up binaries?

**Comment by hunterwilliams** [comment]
hmmm that could be it. May have to ignore them in the replace.

**Comment by jenbreese** [comment]
I got this fix and it is working for me now as well.
