### ISSUE TITLE
Loading Sample Data : import-sample-data.options not found

### ISSUE THREAD

**Issue by vijrej** [marklogic/slush-marklogic-node#195]
I am setting up slush-marklogic-node for the first time. I followed all the steps:
1)Create Sample App
2) specified http and rest and xcc port
3)able to login and browse to the website by specifying app port.
 
The only issue which I am struck with, is that I am not able to load sample data [300 son documents]. I am getting below error

$ : ./ml local mlcp -option_file import-sample-data.options results in below error:
-------------------------------error-----------------------------------------------------
ERROR: Option file /Users/vishtahil/Projects/testmark/deploy/import-sample-data.options not found.
ERROR: ["/Users/vishtahil/Projects/testmark/deploy/lib/server_config.rb:1104:in `block in mlcp'", "/Users/vishtahil/Projects/testmark/deploy/lib/server_config.rb:1073:in `each'", "/Users/vishtahil/Projects/testmark/deploy/lib/server_config.rb:1073:in `mlcp'", "deploy/lib/ml.rb:155:in `<main>'"]
--------------------------------error----------------------------------------------------
The file "import-sample-data.options" exists in root directory, I am not sure why the ruby script is looking under deploy directory.

**Comment by grtjn** [comment]
Looks like a typo. It needs to be `-options_file` with an s..

**Comment by vijrej** [comment]
Correct. There is bug in the documentation. 

NOTE: Change $app-role in import-sample-data.options to your app's role (You can discover that with ./ml local info)

./ml local mlcp -option_file import-sample-data.options
Or on Windows:

ml.bat local mlcp -option_file import-sample-data.options

After fixing the typo I am getting below error
log4j:WARN No appenders could be found for logger (com.marklogic.contentpump.ContentPump).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by grtjn** [comment]
Ah yes, that means you are running with MLCP-1.3-3, and master version of Roxy, not dev. If it bothers you, upgrade to Roxy dev: `./ml upgrade --branch=dev`. Hoping to get that fix into master asap though..
