### ISSUE TITLE
README gets replaced by Roxy one..

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#197]
We need to somehow preserve our copy of the README, and overwrite the Roxy one, after Roxy is done.. Maybe rename it to _README, and rename it back after Roxy? We seem to do that for other files too..

**Comment by hunterwilliams** [comment]
README.mdown is the copied version from the template. Not sure what you mean

**Comment by grtjn** [comment]
Hmmmm......

Ah, wait. I know what happened. I did a Roxy upgrade, which in turn replaced the README with a Roxy copy. Maybe consider having Roxy not replace README on upgrade. Opened a ticket against Roxy for this: https://github.com/marklogic/roxy/issues/519

**Comment by grtjn** [comment]
Closing this one!
