### ISSUE TITLE
Upgrade npm dependencies to latest

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#200]
Bower dependencies were updated, but npm not yet. I think we should:

```
MacPro-2463:test2 gjosten$ npm outdated
Package                   Current   Wanted      Latest  Location
body-parser                1.13.3   1.14.0      1.14.0  body-parser
browser-sync                2.9.1    2.9.3       2.9.3  browser-sync
del                         1.2.1    1.2.1       2.0.2  del
gulp                       3.8.11   3.8.11       3.9.0  gulp
gulp-autoprefixer           2.3.1    2.3.1       3.0.1  gulp-autoprefixer
gulp-bytediff               0.2.1    0.2.1       1.0.0  gulp-bytediff
gulp-filter                 2.0.2    2.0.2       3.0.1  gulp-filter
gulp-flatten                0.0.4    0.0.4       0.2.0  gulp-flatten
gulp-inject                 1.5.0    1.5.0       2.2.0  gulp-inject
gulp-jscs                   1.6.0    1.6.0       2.0.0  gulp-jscs
gulp-less                   1.3.9    1.3.9       3.0.3  gulp-less
gulp-print                  1.1.0    1.2.0       1.2.0  gulp-print
gulp-rev                    5.1.0    5.1.0       6.0.1  gulp-rev
gulp-uglify                 0.2.1    0.2.1       1.4.1  gulp-uglify
karma                     0.12.37  0.12.37      0.13.9  karma
karma-coverage              0.4.2    0.4.2       0.5.2  karma-coverage
karma-jasmine               0.1.6    0.1.6       0.3.6  karma-jasmine
karma-mocha                0.1.10   0.1.10       0.2.0  karma-mocha
karma-phantomjs-launcher    0.1.4    0.1.4       0.2.1  karma-phantomjs-launcher
mocha                       2.3.0    2.3.2       2.3.2  mocha
wiredep                     2.2.2    2.2.2  3.0.0-beta  wiredep
yargs                       1.3.3    1.3.3      3.25.0  yargs
```

**Comment by joemfb** [comment]
Keep in mind, you only need to update the dependences in package.json if the desired version doesn't match the semver selector.

`~1.0.0` matches any newer patch version: `1.0.0`, `1.0.1`, `1.0.2`, etc.
`^1.0.0` matches any newer minor version: `1.0.0`, `1.1.0`, `1.2.0`, etc.

There are more complicated range selectors available as well. You can explore at http://semver.npmjs.com/.

**Comment by grtjn** [comment]
I think we should take a coherent set of close to latest versions, run plenty tests with that, and add ~ in front of all to finish off. We can debate whether we should use ^ or even something more progressive.

**Comment by hunterwilliams** [comment]
Think I solved this.

**Comment by grtjn** [comment]
Accidentally closed by wrong comment line, that should have read #222..

**Comment by grtjn** [comment]
We already use ^ in most places. Looks like the impact doesn't have to be as large as first thought. We have all effectively been testing with latest minor versions for most dependencies already.

**Comment by grtjn** [comment]
I think I combed through pretty thoroughly, anyone care to take a look at PR #305, and maybe do a quick test with it?
