### ISSUE TITLE
Npm install of browser-sync seems to break on Windows (7)

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#206]
Browser-sync depends on components like node-gyph, that need Visual C++ runtime libraries: http://www.browsersync.io/docs/#windows-users

Looks like you need to make sure to have that available. Seen at least one report where running latest slush broke at browser-sync on Windows 7. Maybe because of this, not entirely sure..

Anyone else seen this? I'll see if I can run a test on a win8 machine..

**Comment by grtjn** [comment]
PS: instead of installing entire Visual Studio, like suggested by browsersync.io, I think this should suffice too, if really needed: https://support.microsoft.com/en-us/kb/2977003

**Comment by hunterwilliams** [comment]
Maybe just add a wiki page for possible broken pieces? I feel like asking a developer to install a developer tool is a fine solution.

**Comment by janmichaelyu** [comment]
I got this to work by installing python 2.7.+

**Comment by grtjn** [comment]
Keeping this open for the moment in case others have issues too. Sounds like a docs update, but need more feedback..

**Comment by xbonnamy** [comment]
Run into the same issue.

**Comment by grtjn** [comment]
Talked with @xbonnamy offline, and the solution that worked for him was to install Visual Studio 2013 (make sure to include c++/c# features), then run the generator as usual, then go inside the project folder, and run:

- npm install browser-sync --msvs_version=2013
- npm install

To be safe, you might also want to run `bower install` after that.

**Comment by grtjn** [comment]
From the looks of it you can safely use that `--msvs_version=2013` param on all commands npm commands, even on Mac (without Visual Studio). Maybe add that to the npm install step in the generator by default?
