### ISSUE TITLE
Clashes when running two instances of slush generated sites

### ISSUE THREAD

**Issue by jenbreese** [marklogic/slush-marklogic-node#211]
I am not able to run two separate sites generated by slush at the same time. The second site started will show content from the first site started. If run separately, they work fine.  I also did a full update of slush to make sure it wasn't a legacy bug. I still get the same error.

The second site shows the following error when using "gulp serve-local":

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at Server.listen (net.js:1138:5)
    at EventEmitter.listen (/Users/jbreese/Sites/summer/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/jbreese/Sites/summer/node-server/node-app.js:63:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[14:57:42] *** nodemon crashed: script crashed for some reason
[14:57:42] [nodemon] app crashed - waiting for file changes before starting...
[gulp-patterns] Browser Connected: Firefox, version: 40.0

**Comment by hunterwilliams** [comment]
Could be that they try to have the same browser sync port. Will investigate

**Comment by jenbreese** [comment]
They open on 3000 and 3002. Thanks for looking at it.

**Comment by hunterwilliams** [comment]
Replicated the issue easily. Now can look into the solution

**Comment by hunterwilliams** [comment]
https://github.com/BrowserSync/browser-sync/issues/727 So it is already listed as a bug. 
**Two quick solutions:**
* Add ``ui:false,`` to ~line 593 of your generated gulpfile.js. This turns off the control ui for browersync
* Add ``ui:{
      port: 3045
    },`` to ~line 593 of your generated gulpfile.js. This changes the ui port. Feel free to put any open port. This hosts the browsersync control ui on another port.

**Comment by jenbreese** [comment]
Great. Thanks @hunterwilliams. Should it be added to the documentation?

**Comment by hunterwilliams** [comment]
Probably need a wiki page with all of the possible issues you may encounter.

**Comment by jenbreese** [comment]
+1

**Comment by hunterwilliams** [comment]
I don't have write access to do so, but I'll go ahead and make a document locally and forward to whomever

**Comment by jenbreese** [comment]
Sounds great. I can coordinate getting it into the wiki if I don't have permission.

**Comment by grtjn** [comment]
I have given Hunter access. But you may want to check with Patrick about wiki updates..

**Comment by jenbreese** [comment]
@grtjn Good. I tried editing the wiki and it seems to have worked. But better it comes from the source rather than second hand.

**Comment by hunterwilliams** [comment]
@grtjn / @jenbreese I'm making the wiki page on my fork for now and will email Patrick and ask him to take a look

**Comment by grtjn** [comment]
Are we really using that browser-sync UI? `ui: false` makes sense to me. I think we really only care about the auto-refresh at the moment. That should not depend on that ui being available?

**Comment by hunterwilliams** [comment]
I don't but I'm sure it's useful in some scenarios. Just not sure what
