### ISSUE TITLE
Node.js flagged as virus

### ISSUE THREAD

**Issue by janmichaelyu** [marklogic/slush-marklogic-node#212]
![2015-09-22 18_22_51-officescan notification message](https://cloud.githubusercontent.com/assets/12621739/10016695/77ff563e-615b-11e5-903e-8ca242811345.png)

**Comment by dmcassel** [comment]
Looks like a false positive to be reported to OfficeScan.

**Comment by grtjn** [comment]
Noted for posterity. Can't really do anything about this. Closing ticket..
