### ISSUE TITLE
Add local.json and mlpm_modules to gitignore

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#214]
We renamed gulp-local.json to local.json, but forgot about the .gitignore. mlpm_modules is less common, but something you want to exclude nonetheless by default..

**Comment by joemfb** [comment]
I'd recommend committing mlpm_modules. It's a simple (and usually small) directory structure, so it doesn't really hurt anything. Also, there isn't really an SLA for the registry at this time.

**Comment by grtjn** [comment]
Hmm, shouldn't we start making backups and such of that registry? :)

**Comment by joemfb** [comment]
Wrote this hours ago, but never submitted it ...

I think uptime is what's relevant to this issue, but yeah, regular backups should be taken. It's been manual and spotty so far. I've opened an issue on the registry project
