### ISSUE TITLE
Enabling blue design breaks gulp serve-prod

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#221]
```
[00:28:56] Plumber found unhandled error:
 Error in plugin 'gulp-minify-css'
Message:
    Broken @import declaration of "https://fonts.googleapis.com/css?family=Lato:300,400,700" - timeout
Details:
    fileName: /space/projects/github-search.live/ui/styles/app.css
[00:28:56] Plumber found unhandled error:
 Error: no writecb in Transform class
```

Simplest way out is to just disable that line in `ui/styles/blues.less`..

**Comment by jenbreese** [comment]
@grtjn It is very ugly without that font. Why wouldn't it break on gulp serve-local or gulp serve-dev but it does on prod? If the best solution is to remove the font, then i need to find another font because it is too ugly to live without the Lato. What is your recommendation?

**Comment by hunterwilliams** [comment]
Think I may know a fix for this.

**Comment by hunterwilliams** [comment]
Got it. https://github.com/jakubpawlowicz/clean-css which gulp-minify-css wraps provides processImportFrom which allows blacklisting imports, which was added in support of this very issue: https://github.com/jakubpawlowicz/clean-css/issues/632

**Comment by grtjn** [comment]
Yeah, to summarize, gulp serve-dev/prod makes the css go through a minify for optimization, and that choked on the google fonts link. By skipping that the issue was solved..
