### ISSUE TITLE
Account Edits Not Properly Saved

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#229]
Affects Master

Not a very big deal as it doesn't affect functionality negatively. Have to get in weird use case

Recreation
1. Login
2. Edit Account details and submit
3. Verify new details on page
4. Refresh the page & now changes appear to be *missing*
5. Logout & log back in
6. Changes are now *present*

Behind the scenes
* Edits are saved locally and then sent to the server
* Since edits are local they are dropped on refresh but live in the database
* /api/user/status serves the user from session variable and is only updated upon login

Potential issue if user edits account refreshes -> then will not see edits or will override existing edits if they hit submit again.

**Comment by grtjn** [comment]
Ah yes, I did see that one. There is actually a TODO for that in proxy.js, to capture user profile update in the session object as well.. :)

**Comment by hunterwilliams** [comment]
I'll see if I can just tack in onto to my passport modifications as that already touched this area a bunch

**Comment by grtjn** [comment]
Might be nice to have that in 0.2.0. I tagged the passport stuff for 0.2.1..

**Comment by hunterwilliams** [comment]
Alright. My thought is to make ``/api/user/status`` do a fresh pull from MarkLogic each time. It's an extra call, but the app shouldn't be asking for status often.

**Comment by grtjn** [comment]
Works too. If you reached nodejs, going to ML is not that much further..

**Comment by grtjn** [comment]
But that means we could drop profile from session, right? Cleaner perhaps..
