### ISSUE TITLE
Push ESRI support into separate component

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#233]
ESRI option was taken out of the wizard, but the functionality should not get lost. We just need to push it into a bower component, and make sure the steps to enable it manually are listed.

**Comment by daveegrant** [comment]
I think we can close this ticket.  A separate ESRI component has been that complies with the new modules approach can be found at (https://github.com/daveegrant/ml-esri-maps-ng).  Instructions for using it are at (http://daveegrant.github.io/ml-esri-maps-ng/).

**Comment by grtjn** [comment]
Thnx for the links, closing this ticket..
