### ISSUE TITLE
XML preview in detail page not using syntax highlights

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#245]
Copied from #131:

Hmm, PR #230 makes it possible to use hljs instead of pre. If you enable the 'hljs' library in detail.module.js, and then add `hljs source="ctrl.xml" language="xml"` to the `<pre>` elements, you can see how that looks. Unfortunately hljs like putting things in backgrounds, which is what the pre-xml class is trying to get rid off.

@jenbreese WDYT, does it make sense to use hljs, and can we fix the presentation? Or stick with the pre for the moment? hljs just adds color, nothing else..

In more general (to all), also thinking, is there a better library than hljs for viewing xml? With not only color, but also collapsable like the json-explorer is showing json?

**Comment by jenbreese** [comment]
@grtjn Let's talk about this tomorrow?

**Comment by grtjn** [comment]
You can ping me on IM.. :)

**Comment by janmichaelyu** [comment]
PR #276 should resolve this. I discovered that using
```html 
<pre source="ctrl.xml" language="xml"></pre>
```
wasn't working and some hljs documentation was outdated.

**Comment by grtjn** [comment]
I notice now that my description in the top didn't include the `hljs` in the suggested addition to `<pre>`. That attribute is essential..

**Comment by grtjn** [comment]
One year further, and a lot has happened in between. I have recently released the view-file-ng component (https://grtjn.github.io/view-file-ng/#/), would that be a better solution for out of the box display of json, xml, text, and binary, both raw and pretty, and with a download button as well?

@janmichaelyu / @jenbreese WDYT?

**Comment by grtjn** [comment]
Discussed with @jenbreese offline, we are adding view-file-ng in cards theme release..

**Comment by grtjn** [comment]
Fixed in cards-theme branch
