### ISSUE TITLE
Prepend app-specific ML users with app-name

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#246]
And make middle-ware add that automatically to user names, so end users don't need to type the prefix in the login box..

It can be seen as a good practice to prevent user conflicts when deploying multiple demos on a single server.

**Comment by hunterwilliams** [comment]
So they'd just type user?  And it'd make it sample-app-user?  That seems quite odd behavior for tracking issues later

**Comment by grtjn** [comment]
It prevents all kinds of potential conflicts with users between multiple demos (deployed in one server), as well as conflicts with built-in users like 'nobody', 'admin', etc. How do you mean odd?

**Comment by hunterwilliams** [comment]
I guess we prevent them from having to type sample-app-user, but from an ops perspective they say they're using one name you're verifying another on MarkLogic. Also if you need another user for an app you have to remember to name it correctly or it won't work. Room for human or middleware error to save a couple keyboard presses once before they save their password to the browser.

**Comment by grtjn** [comment]
It is not really meant for saving typing characters in the UI, but prevent conflicts with users defined in ML for other purposes. Now if people create custom/adhoc users for a demo they tend to not add such a prefix. Adding such a prefix is just a good practice. It does mean that the dev or operator needs to keep in mind that such a prefix is necessary, but that is just a matter of education.

Note: samplestack does it as well..

**Comment by grtjn** [comment]
PR #298 allows enabling a flag in the middle-tier that forces login to only accept user names that start with app-name + '-'. It is optional though, and not enabled by default.
