### ISSUE TITLE
Bump Task Broken

### ISSUE THREAD

**Issue by hunterwilliams** [marklogic/slush-marklogic-node#247]
Affects: Current release/master

Doesn't look like gulp-bump is in the package.json. Not sure if it's intended to remove the functionality or it somehow got dropped from the pacakge.json.

``gulp bump`` fails to find $.bump

**Comment by grtjn** [comment]
Gulp bump is new actually, so I think we simply forgot to add the dependency. Or it fell off during sorting/merging somewhere?
