### ISSUE TITLE
Unsuitable resolution declared for angular: 1.4.6

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#251]
1.4.7 has been released apparently, so now the hard-coded resolution does no longer work. Afraid this calls for an urgent release..

**Comment by joemfb** [comment]
Which dependencies conflict and require a resolution?

**Comment by grtjn** [comment]
We need to fix this asap. I'm thinking of releasing a patch release..

**Comment by grtjn** [comment]
Regarding conflict resolution. If you run `bower install angular --save`, it will tell you:

```
Unable to find a suitable version for angular, please choose one:
    1) angular#~1.3.0 which resolved to 1.3.20 and is required by angular-x2js#0.2.0
    2) angular#~1.x which resolved to 1.4.7 and is required by angular-ui-tinymce#0.0.9
    3) angular#>=1.3.0 which resolved to 1.4.7 and is required by angular-bootstrap#0.13.4
    4) angular#1.4.7 which resolved to 1.4.7 and is required by angular-cookies#1.4.7
    5) angular#~1.4.7 which resolved to 1.4.7 and is required by auto-recall
    6) angular#>1.0.8 which resolved to 1.4.7 and is required by angular-highlightjs#0.4.3
    7) angular#>= 1.0.8 which resolved to 1.4.7 and is required by angular-ui-router#0.2.15
    8) angular#^1.4.1 which resolved to 1.4.7 and is required by ml-search-ng#0.2.2
    9) angular#>=1.3.8 which resolved to 1.4.7 and is required by bardjs#0.1.8
    10) angular#~1.4.7 which resolved to 1.4.7
```

So, looks like angular-x2js is the culprit. Maybe provide an override for that, to prevent this..

**Comment by joemfb** [comment]
angular-x2js looks like some kind of performance art ;)

Here's the whole package: https://github.com/cesarbarone/angular-x2js/blob/master/src/x2js.js. I'm not sure we need a dependency for that, and certainly not if it's causing conflicts.

**Comment by grtjn** [comment]
It is used on the detail page..

**Comment by joemfb** [comment]
Right, but we could just use x2js directly; it has it's own bower package. The angular-x2js package is a ~3 line wrapper. We could just use x2js in the controller, or wrap it in a service in our codebase ...

**Comment by grtjn** [comment]
I'd welcome a PR.. :)

**Comment by gjwilson21** [comment]
Hi, Any update on this issue? I am getting the same error when I run slush on my macbook. 

bower angular                         resolution Unsuitable resolution declared for angular: 1.4.7
bower                                  ECONFLICT Unable to find suitable version for angular

Thanks
Joel

**Comment by grtjn** [comment]
Yeah, this needs to be fixed. We should change the pattern into ~1.4.1. And deal with angular-x2js..

**Comment by grtjn** [comment]
PR #293 fixes angular resolution, and there is already an override for angular-x2js..
