### ISSUE TITLE
List slush version somewhere

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#257]
slush-version.txt perhaps..

**Comment by joemfb** [comment]
It's in package.json, can't consumers just check there?

**Comment by grtjn** [comment]
The package.json in the generated project contains 0.0.0..

**Comment by joemfb** [comment]
Whoops ... ;)

Maybe just make it match the overall version as part of the release process?

**Comment by grtjn** [comment]
Ot just a sentence in the project readme. Generated with slush-marklogic-node v...
