### ISSUE TITLE
creating Admin user account breaks login

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/slush-marklogic-node#258]
Prior to creating any users, I can log in as admin/admin. I do get errors in the MarkLogic ErrorLog about not finding /api/users/admin.json

After clicking 'Account' within the app and creating a user with the attributes: fullname 'Admin', email 'admin@example.com', I find myself no longer able to login. My current session is ok, but as soon as I lose it (switch to another browser, eg), I cannot log in again and the app becomes unusable.

Deleting the /api/users/admin.json file from my content db resolves the issue (though the original errors reappear).

**Comment by grtjn** [comment]
Could parsing of the profile in nodejs go wrong, and cause issues? Does the express service log anything to console?

**Comment by patrickmcelwee** [comment]
The express service log just logs

POST /api/user/login - - ms - -
code: 200

which I doubt is super helpful

**Comment by patrickmcelwee** [comment]
I am running Node 0.10.40 ... maybe I need to upgrade?

**Comment by narmi91** [comment]
Yes, I tried 0.12 and this didn't work either. Needed to move to 4.x.

Here is the cheat sheet so far.


# ===================== INSALL SLUSH NODE APP FRAMEWORK
======================
# install nodejs
#
https://www.digitalocean.com/community/tutorials/how-to-install-and-run-a-node-js-app-on-centos-6-4-64bit
sudo yum -y groupinstall "Development Tools"
# strt and detach sessions
sudo yum -y install screen
# get source
sudo wget
http://nodejs.org/dist/latest-v0.12.x/node-v0.12.7-linux-x64.tar.gz
#
http://serverfault.com/questions/698002/install-node-0-12-x-binaries-on-centos-7
cd /usr/local && sudo tar --strip-components 1 -xzf
/usr/src/node-v0.12.7-linux-x64.tar.gz --exclude=ChangeLog
--exclude=LICENSE --exclude=README.md
cd /usr/local && sudo tar --strip-components 1 -xzf
/usr/src/node-v4.2.1-linux-x64.tar.gz --exclude=ChangeLog --exclude=LICENSE
--exclude=README.md
#clear PATH program hashes
hash -r
node --version
npm --version
# install new npm
sudo /usr/local/bin/npm install -g npm
# install gulp for some reason need to use full path w/sudo /usr/local/bin
su
npm install -g gulp
npm install -g slush
npm install -g bower
npm install -g slush-marklogic-node
exit
#install RVM (ruby manager) from http://rvm.io
gpg --keyserver hkp://keys.gnupg.net --recv-keys
409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable
vim /etc/group #add admin,root to rvm group
source /etc/profile.d/rvm.sh
exit
exit
#relogin
su
rvm list known
#check autoconf version
autoconf --version
# updated to at least 2.67
wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar xvfvz autoconf-2.69.tar.gz
cd autoconf-2.69
./configure
make
sudo make install
# install latest stable ruby
rvm instal ruby-2.2
exit
exit
#relogin


#create node
su
slush marklogic-node demo01
cd demo01
cd deploy
vim ml-config.xml
#remove deplicate eyeColor range-element-indexes if necessary

vim build.properties
#edit authentication-method=digestbasic # remove the extra basic:

cd .. #back to demo01 directory
./ml local bootstrap
./ml local deploy modules
bower install
npm install
gulp serve-local
# port 3000 and port 9070 get setup

#edit build.properties or better yet local.properties to set MLCP root
cd

# install charts
bower install --save ml-highcharts-ng


Regards,
-imran
@imrantech
240.230.7860

**Comment by joemfb** [comment]
I'd recommend adding a bunch of `console.log` statements to the `/user/status/` route handler in `node-server/routes.js`.

What do you mean by "the app becomes unstable"?

**Comment by patrickmcelwee** [comment]
it hangs when I submit login information
I'll try to dig in with log statements when I have time (prob next week)

**Comment by grtjn** [comment]
Re @narmi91: duplicate eyeColor should normally not happen. I heard it was caused by running slush marklogic-node twice for same app? But removing 'basic' might cause you trouble. To my knowledge, the nodejs tier still uses basic auth (by default).

And if you are interested in using digital ocean, you might wanna reach out to @Audarth (Nish Bakshi), who has integration of mlvagrant with digitalocean running. Can save you some manual steps..

**Comment by grtjn** [comment]
Anyhow, still a little surprised about this. Haven't seen this myself, and see no obvious reason for this to fail. Does this fail for any user profile, or just admin specifically?

**Comment by patrickmcelwee** [comment]
OK, thanks for prompting me to dig into this. This was originally a problem with the [gulp-nodemon library](https://github.com/JacksonGariety/gulp-nodemon/issues/67)

 If I waited long enough on node v0.10.x (~2-3 minutes), gulp aborted with this error:

```
/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/index.js:74
    cp.spawnSync(process.platform === 'win32' ? 'gulp.cmd' : 'gulp', tasks, {
       ^
TypeError: Object #<Object> has no method 'spawnSync'
    at run (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/index.js:74:8)
    at /Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/index.js:56:19
    at Array.forEach (native)
    at null.<anonymous> (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/index.js:55:23)
    at emit (events.js:117:20)
    at restartBus (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:161:7)
    at EventEmitter.filterAndRestart (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:144:16)
    at EventEmitter.emit (events.js:95:17)
    at EventEmitter.<anonymous> (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/node_modules/nodemon/node_modules/chokidar/index.js:151:15)
    at EventEmitter.FSWatcher._emit (/Users/pmcelwee/work/dev/hebrew/node_modules/gulp-nodemon/node_modules/nodemon/node_modules/chokidar/index.js:179:5)
```

This was [reported](https://github.com/JacksonGariety/gulp-nodemon/issues/67) as  an incompatibility with node < 0.12. *So I upgraded Node to 0.12, and stopped getting this gulp-nodemon error. We may need to document that slush is not compatible with Node < 0.12.*

However, it still didn't work. In the gulp output while running node v0.12.7 and v4.2.2, I just got this over and over again (about once a minute or two): 

```
[gulp-patterns] [proxy error] socket hang up
POST /api/user/login - - ms - -
code: 200
```

Taking @joemfb's advice, I looked into the node router (while running v4.2.2), and found that, while route `/user/login` sets `req.session.user` correctly, by the time it gets to route `/user/status`, `req.session.user` is undefined. I'll keep looking, but any ideas are welcome.

**Comment by patrickmcelwee** [comment]
CORRECTION: I was misinterpreting the log statements, in the `/user/login` route, this never resolves:

```javascript
        response.on('data', function(chunk) {
```

**Comment by grtjn** [comment]
You are talking about https://github.com/marklogic/slush-marklogic-node/blob/master/app/templates/node-server/routes.js#L105, right? That is interesting. We have used user profiles very often, never any problem, but maybe that was with older slush template?

**Comment by patrickmcelwee** [comment]
Yes that's the right line ... I think I generated this app with close to the latest slush, no more than 3 weeks ago. (In particular, my `node-server/routes.js` is identical to the current master version.) 

Did you mean that you never had problems with older slush versions? I notice that line 105 and a bunch of other code in this file was added Sept. 25

So, for some reason, the 'data' event is not called on `response` after this watcher is created. I checked, and the `end` event *is* called. I have never worked with express before, and in the time I had yesterday, I wasn't able to figure out how to get a handle on the data.

**Comment by grtjn** [comment]
I think the history on that file is a bit polluted because of the major rework that Paxton did. You can see a more original version of that part here: https://github.com/marklogic/demo-cat/blob/master/server.js#L108

**Comment by grtjn** [comment]
Could things have changed under the covers? Difference in behavior with newer nodejs versions?

**Comment by patrickmcelwee** [comment]
Found it. The problem was that I had set up a default transform with <document-transform-out>. NEVER AGAIN!

I may think about how to catch this error and present the user with an appropriate error message.
