### ISSUE TITLE
Initial Login not working or not known by me.

### ISSUE THREAD

**Issue by packetsdontlie** [marklogic/slush-marklogic-node#260]
I've completed the steps listed in the README.mdown

https://github.com/marklogic/slush-marklogic-node/blob/master/README.mdown

My app server has started and I see the home page.  When I click on the login button, I'm taken to 

http://localhost:3000/login

I've put in the admin user for my local Mark Logic server and that was not accepted.

I used the same admin user to create another user on http://localhost:8001/user-summary.xqy?section=security

I gave this user the role created by Roxy for the application user.  In this case, Roxy created the haircut-user with the haircut-role.  My new user, "pyramid" also has the haircut-role.  I tried to login with that as well to the slush app, but it does not work.  I've also tried admin/admin since it was listed in a previous issue for this project.  That did not work either.  Did I mss this in the docs?

**Comment by grtjn** [comment]
If you had a wonkt local.properties, then your local.json might be bad too. Does that contain correct settings?

**Comment by packetsdontlie** [comment]
That seems to have done it.  I changed the port in local.json and it now authenticates me.  Thank you.
