### ISSUE TITLE
lint/test errors shouldn't always abort the build

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#267]
At the very least, there needs to be an options to continue anyway. Run into this doing deployments an deadline; always fun to be forced to fix unit tests at the last minute ...

**Comment by grtjn** [comment]
I vote for a `--novet`, that effectively skips the jshint and jscs validation in the `vet` task, or make it continue without abort.

You can also disable things manually, but then it is permanent. The minimum to get past js syntax issues without aborting is commenting out the last two lines of the `vet` task:

```
gulp.task('vet', function() {
  log('Analyzing source with JSHint and JSCS');

  return gulp
    .src(config.alljs)
    .pipe($.if(args.verbose, $.print()))
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish', {verbose: true}))
//    .pipe($.jshint.reporter('fail'))
//    .pipe($.jscs())
  ;
});
```

**Comment by grtjn** [comment]
Or maybe gulp build should not vet, unless `--vet` was provided? (any votes?)

**Comment by grtjn** [comment]
I added an `--ignoreErrors` feature as part of #305..

**Comment by joemfb** [comment]
Great, that works for me!
