### ISSUE TITLE
minified build needs sourcemaps

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#268]
debugging the minified build (when it exhibits behavior different from dev-mode) is *very* difficult. We need to generate sourcemaps along with minified assets

**Comment by grtjn** [comment]
Does #305 include the changes needed for this?

**Comment by joemfb** [comment]
Looks like it to me; have you verified that `.map` files are generated? Do the right src files show up in the browser when debugging a minified build?

**Comment by grtjn** [comment]
I do get .map files, haven't tried looking with browser. What would be an easy way to do that?

**Comment by joemfb** [comment]
While running a `dist/` build, check to see if console logs, errors, or breakpoints link/show the individual JS files, as opposed to the concatenated bundle (sourcemaps are enabled by default in Chrome, not sure about other browsers).

**Comment by grtjn** [comment]
I think I got it working, to some extent at least. I see the minified js/css with a comment of which map file is associated with each, and then an extra source/ folder with the non-minified files. It doesn't show the individual files, but the concatenated version, but at least it is not minified/uglyfied..

**Comment by grtjn** [comment]
Fixed as described in #305, closing for now..
