### ISSUE TITLE
REST API proxy doesn't support multipart requests

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#270]
I've had to implement custom endpoints to support multipart requests; it'd be much better to just use the REST API endpoints where appropriate

**Comment by mariannemyers** [comment]
I've also had to do this recently.  I found node-http-proxy to be a simple solution, as sophisticated proxying can look as simple as this (after some initial, lightweight setup):

<pre>
function proxy(req, res) {
  req.headers.Authorization = getBasicAuth(req.session);
  mlProxy.web(req,res);
}
</pre>

**Comment by joemfb** [comment]
To do this right, we should also look at limiting the express bodyparser and other middleware to custom routes, but maybe that should be another ticket ...

**Comment by grtjn** [comment]
See also #31 and #189..

**Comment by grtjn** [comment]
Marking this as bug, as I think the proxying should be non-limiting out of the box..

**Comment by grtjn** [comment]
Is this a duplicate of #31?

**Comment by grtjn** [comment]
I fixed #31 with PR #189, which should also fix this. Closing this for now..
