### ISSUE TITLE
gulpfile should be made more explicit

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#271]
The gulpfile is currently quite complicated, as it auto-imports and groups plugins, reads config files, etc. It should be made explicit, and well-documented. If this were a framework, it'd be fine to black-box the build process, but it's an application generator, and the build process often needs to be customized.

**Comment by grtjn** [comment]
@joemfb Can you come up with more concrete suggestions? Once your thoughts are clear, maybe split into specific tasks..

**Comment by joemfb** [comment]
This is two things: a plea to remove (or at least simplify) `gulp.config.js`, and an ongoing reminder that I find the current gulpfile to be really complicated ;)

It seems like the "gulp community" has moved to `gulp-load-plugins`, and nodemon/browersync seem useful to a lot of people... I guess what I want is some well-document ways to simplify what's running; `--nosync` and `--ignoreErrors` are a good start.

We can close this; I'll open more specific tickets as they occur to me.

**Comment by grtjn** [comment]
I do agree the gulp config is pretty large, the gulpfile seems reasonably okay to me now. Maybe Matt has some good thoughts on the gulp config?
