### ISSUE TITLE
`gulp build` breaks `gulp serve-dev`

### ISSUE THREAD

**Issue by joemfb** [marklogic/slush-marklogic-node#272]
Running `gulp build` removes the compiled CSS, so an app instance served by `gulp serve-dev` suddenly loses it's style.

**Comment by grtjn** [comment]
+1

**Comment by grtjn** [comment]
Doesn't gulp build eventually produce a new css?

**Comment by grtjn** [comment]
Nope, serve-local et al rely on .tmp/main.css, and that gets flushed at the end of gulp build. Getting rid of that cleanup at the end, as gulp build cleans that at start as well.

**Comment by grtjn** [comment]
Fixed in #305..
