### ISSUE TITLE
app-port empty by default in local.properties

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/slush-marklogic-node#275]
I just created a fresh slush-marklogic app from the packaged version (accepting all defaults) and got a local.properties that looked like this:

```properties
#################################################################
# This file contains overrides to values in build.properties
# These only affect your local environment and should not be checked in
#################################################################

#
# The ports used by your application
#
app-port= 
# Taking advantage of not needing a XCC Port for ML8
xcc-port=${app-port}
install-xcc=false

#
# the uris or IP addresses of your servers
# WARNING: if you are running these scripts on WINDOWS you may need to change localhost to 127.0.0.1
# There have been reported issues with dns resolution when localhost wasn't in the hosts file.
#
local-server=localhost
#
# Admin username/password that will exist on the local/dev/prod servers
#
user=admin
password=admin
```

Maybe that would be solved with the latest code, but don't have time to check at the moment, so wanted to create a placeholder here.

**Comment by patrickmcelwee** [comment]
I should mention that this causes `./ml local bootstrap` to fail with error message:

```
Bootstrapping your project into MarkLogic 8 on db...
ERROR: XDMP-LEXVAL: gr:port("") -- Invalid lexical value ""
See MarkLogic Server error log for more details.
ERROR: ... Bootstrap FAILED
```

**Comment by grtjn** [comment]
Sounds very a-typical. I have never observed this, nor heard anyone else about this. Did something strange happen while the generator was working on this? And are you able to reproduce this consistently at your end?

**Comment by patrickmcelwee** [comment]
You're right ... I just tried again and did not see this. Maybe I accidentally entered a space when I got the port question from the generator. Closing this.
