### ISSUE TITLE
'marklogic-node' not found!

### ISSUE THREAD

**Issue by tenou** [marklogic/slush-marklogic-node#290]
Hi there!
I am new to Marklogic, can do only simple querying on console and such.Then I found this application generator and want to try it out. I have already installed all the dependencies and the slush-marklogic-node. But then I encounter error on creating new application:
#slush marklogic-node demo
[slush] No generator by name: "marklogic-node" was found!
[slush] Try installing it with `npm install -g slush-marklogic-node` first.

What do I need to take action for this?
P.S. I'm using Ubuntu 14.04.

Thanks,
tenou

**Comment by patrickmcelwee** [comment]
Tenou,

Did the `npm install -g slush-marklogic-node` finish successfully?

**Comment by grtjn** [comment]
Note: you may need to run that with sudo. Only do so for global installs (with the -g param)..

**Comment by tenou** [comment]
@patrickmcelwee Yes, it is installed successfully. 
@grtjn I also run it with sudo but same thing happened

**Comment by grtjn** [comment]
@tenou What is the console output of `slush`?

It should be something like:

```
$ slush
[slush] Installed generators
[slush] ├── marklogic-node (1.0.1)
[slush] └── node (0.2.1)
```

**Comment by tenou** [comment]
Nope..there's no such thing. only angularjs is showing.

But when I checked in my root directory, under npm, there is slush-marklogic-node installed in there

**Comment by patrickmcelwee** [comment]
what is the output of `slush -v`?

**Comment by joemfb** [comment]
You could also check the output of `which slush`, you may have multiple global node.js installations, with separate global npm module locations.

**Comment by tenou** [comment]
@patrickmcelwee Here's the result:
```
$ sudo slush -v
$ [slush] 1.1.1
```

**Comment by tenou** [comment]
@joemfb Result for ```which slush```
```
$ which slush
$ /usr/local/bin/slush
```

**Comment by joemfb** [comment]
Does `ls -lh /usr/local/bin/slush` output:

    /usr/local/bin/slush -> ../lib/node_modules/slush/bin/slush.js

and, if so, is `slush-marklogic-node` in `/usr/local/lib/node_modules/`?

**Comment by grtjn** [comment]
@tenou Was this resolved?

**Comment by grtjn** [comment]
Considering this stale-or-resolved. Closing for now..
