### ISSUE TITLE
Angular bootstrap directive changes

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#319]
Angular bootstrap now prepends all their directive names with `uib-`. We should migrate too, and make sure all still works well.

Snippet selection seems to malfunction in latest slush, (or maybe just in UI templates)..

**Comment by Audarth** [comment]
I'm putting in a pull request that mostly resolves this, however one of the dependencies ml-search-ng still uses typeahead and typeahead-popup mostly in ml-input-html so we'll need to update that component as well!

**Comment by grtjn** [comment]
Maybe open tickets against ml-search-ng for that, and if you have some cycles left open PR's as well? :)

**Comment by Audarth** [comment]
Opened a PR for ml-search-ng for that final directive change!
