### ISSUE TITLE
variable @link-color is undefined

### ISSUE THREAD

**Issue by ChrisDay-Australia** [marklogic/slush-marklogic-node#323]
After doing the slush marklogic-node, ml bootstrap and ml deploy modules, initiating the gulp serve-local, I get the following error:
variable @link-color is undefined in file /Users/cday/projects/mlgeo/ui/styles/admin.less line no. 121

Resolved by adding the variable @link-color to the admin.less file

**Comment by grtjn** [comment]
Which version of slush-marklogic-node?

**Comment by grtjn** [comment]
Occurs in 1.0.2 as well I'm afraid. I knew I should have separated this fix, then it might have ended up as part of 1.0.2:

https://github.com/marklogic/slush-marklogic-node/pull/305/files#diff-5742b86a2f9696e8a3940b9a94854f2d

**Comment by grtjn** [comment]
At the moment, this probably gives the best starting point:

    sudo npm install -g git://github.com/grtjn/slush-marklogic-node.git#hunterwilliams-npm-updates

**Comment by ChrisDay-Australia** [comment]
Just to confirm with you, it is version 1.0.2 of slush-marklogic-node that I am using.

**Comment by grtjn** [comment]
Fixed with PR #305..

**Comment by popzip** [comment]
This is happening for me too...version: slush-marklogic-node@1.0.3
Can you point me to where/how to update the admin.less file?

**Comment by grtjn** [comment]
Odd, pretty sure it was fixed in 1.0.3 release. It is just a one-line code change:

https://github.com/marklogic/slush-marklogic-node/pull/305/files#diff-5742b86a2f9696e8a3940b9a94854f2d
