### ISSUE TITLE
Consider adding ec5/6 polyfill

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#330]
Had a demo today that used String.prototype.startsWith. That worked fine in most, but some customer was still running IE. Maybe a generic polyfill for functions like that could save some issues with demos unexpectedly not running on particular browsers..

**Comment by grtjn** [comment]
I am coming across code like:

```
    <!--[if lt IE 9]>
    <script src="bower_components/es5-shim/es5-shim.js"></script>
    <script src="bower_components/json3/lib/json3.min.js"></script>
    <![endif]-->
```

And in a different demo:

```
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
```

**Comment by jenbreese** [comment]
@grtjn We do need to have the respond.js and the html5 shiv for it to work in Bootstrap. I'm not sure why the difference in the two demos. Here's the link to the Bootstrap documentation on browser support: http://getbootstrap.com/getting-started/#support

**Comment by grtjn** [comment]
Just different polyfills. The latter seems to come directly from Bootstrap: http://getbootstrap.com/getting-started/#template. We should at least copy over that, including viewport and such..

**Comment by joemfb** [comment]
+1 to loading some polyfills by default

**Comment by grtjn** [comment]
Some more good resources: http://html5please.com/, and http://www.creativebloq.com/html5/10-best-polyfills-2133015

**Comment by grtjn** [comment]
Reading through some stuff I think all 4 would make sense, and perhaps mediaelement.js (http://mediaelementjs.com/) as well?

Not sure how to best add them though. You can bower install all, but you probably want that IE version check around. Was also looking at Modernizr, but not sure how you best integrate that with AngularJS. And you probably don't want to load all polyfills/shims..

**Comment by Audarth** [comment]
It also might be good while we're doing this to also put in support for es6, though I'm not sure if polyfills alone would be enough so we might need to get gulp to transpile the es6 code to es5.

There's a few resources for adapting es6, this page has a bunch of different es6 tools https://github.com/addyosmani/es6-tools 

And here's an example using a gulp task to transpile the es6 code to es5 with babel https://github.com/thoughtram/es6-babel-browserify-boilerplate

**Comment by grtjn** [comment]
es6 and transpiling code goes a bit far to my personal opinion. I haven't come across much use cases for es6 features yet. Is there a compelling one?

Maybe save es6 for the ticket to work towards Angular 2 and components..

**Comment by grtjn** [comment]
Would you be willing to take a look at this? I'm thinking of the polyfills in my first comment, and most importantly those matching http://getbootstrap.com/getting-started/#template.

If you have time to dig a bit deeper, that would be great too. What kind of polyfills are used most often in angular apps? See if internet search tells something..

**Comment by grtjn** [comment]
Adding the bootstrap template stuff to cards-theme branch..

**Comment by grtjn** [comment]
Merged into cards-theme branch.
