### ISSUE TITLE
Should we explicitly load jQuery before Angular?

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/slush-marklogic-node#331]
I just read some forums (see [here](http://gjermundbjaanes.com/angular-and-jquery-load-order-matters/) and [here](http://stackoverflow.com/questions/27777108/loading-jquery-after-angularjs-instead-of-before)) that say that, when angular is loaded before jQuery, it automatically loads its own jqLite library. This can cause problems.

[This wiredep thread](https://github.com/taptapship/wiredep/issues/202) indicates that the best solution is to exclude jQuery from wiredep's auto-injection, and just explicitly put it into `index.html`. Not incidentally, this solution would mesh with the solution I am considering for [an issue I ran into in the `ml-lodlive-ng` library](https://github.com/grtjn/ml-lodlive-ng/issues/10). That issue could be solved by explicitly loading both jQuery and the original `ml-lodlive` library before wiredep's injection block.

**Comment by grtjn** [comment]
We solved it by putting jquery above angular in the bower.json dependencies. That seemed enough for all cases that I saw.. It also only matters in cases where jquery needs to interact with angular elements..

**Comment by patrickmcelwee** [comment]
OK, if we aren't seeing problems, then probably no reason to do this.

**Comment by grtjn** [comment]
It wasn't necessary to close it just yet, since the solution is not merged yet. It is included in the dashboard PR though: https://github.com/marklogic/slush-marklogic-node/pull/327/files
