### ISSUE TITLE
update customization wiki

### ISSUE THREAD

**Issue by popzip** [marklogic/slush-marklogic-node#333]
For adding a facet, step 2 search constraint - you can remove the "search" prefix to the example. It looks like the updated search options file does not contain it (made it tricky when i searched that file for the provided example syntax). https://github.com/marklogic/slush-marklogic-node/wiki/Customization-recipes

**Comment by grtjn** [comment]
thnx for reporting!

**Comment by grtjn** [comment]
Looks like this was fixed..
