### ISSUE TITLE
Review ui-themes branch

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#336]
We discontinued the UI PRs in favor of working on the ui-themes branch instead. Please review any comments you made on those PRs yourself against the code that lives the branch, and consider opening PR's for _small_ fixes against that branch..

**Comment by Audarth** [comment]
So I checked out the 3column theme today and I noticed I'm getting an error I've seen before when I navigate to the search page 

angular.js:12783 TypeError: Cannot read property '$on' of undefined
    at MLSearchController.init (http://localhost:3000/bower_components/ml-search-ng/dist/ml-search-ng.js:217:16)
    at MLSearchController.SearchCtrl (http://localhost:3000/ui/app/search/search.controller.js:20:10)

I remember you fixing this one, digging through the emails your one from 23 feb was "It turned out to be the <ui-view/> issue."  I've totally forgotten what this referred to though, tried playing with ui-view in root.html and didn't seem to change anything?

**Comment by Audarth** [comment]
Hmm also it might be easier to have separate issues for each theme?

**Comment by Audarth** [comment]
Also in the dashboard theme there's no create button? And the search box on the left column doesn't seem to do anything? The x/clear() button for the search bar in /search also seems to have a `    margin-right: 35px;` that should probably be removed since it looks a bit odd

**Comment by grtjn** [comment]
You could open PRs (against ui-themes branch) for what you think you can fix yourself (we can always discuss inside the PRs), and add theme specific comments for stuff not covered in such PRs here: #325 (3-column), #326 (map), and #327 (dashboard)..

**Comment by grtjn** [comment]
To run tests with ui-themes you can use:

```sh
sudo npm uninstall -g slush-marklogic-node
sudo npm install -g git://github.com/marklogic/slush-marklogic-node.git#ui-themes
```

**Comment by grtjn** [comment]
Re ui-view: you were close. It was in index.html, not root.html. I'll open a PR to fix it everywhere..

**Comment by grtjn** [comment]
Assigning to Jen to go over styling one last time, and more specifically on the map theme for the small screen/mobile mode..

**Comment by grtjn** [comment]
The branch is pretty much ready for release!

**Comment by grtjn** [comment]
Thanks for all who helped with this! Wrapping up the ui-themes branch!
