### ISSUE TITLE
Add link to community add ons in the README

### ISSUE THREAD

**Issue by aajacobs** [marklogic/slush-marklogic-node#375]
It would be nice if the README directly referenced the community add ons for higher visibility and easy of finding them.

**Comment by patrickmcelwee** [comment]
I am putting together a package of updates to the documentation as part of our partner enablement ... I can roll this great suggestion into that.

**Comment by grtjn** [comment]
Thnx Patrick!

**Comment by grtjn** [comment]
I was happening to touch this, and added the links to recipes and add-ons on the landing page instead..

@patrickmcelwee I am about to push some more elaborate changes to the READMEs..

**Comment by patrickmcelwee** [comment]
Thanks Geert! The partner enablement went in a different direction, and I never circled back to this ...
