### ISSUE TITLE
Guest-access doesn't work with passport

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#397]
If you create a vanilla app, enable guest login, and hit search page, the call to /v1/search fails because passport isn't initialized properly. We need a fix or a temp workaround..

**Comment by grtjn** [comment]
@ryanjdew Could you take a look? You know most about this passport logic I think..

**Comment by ryanjdew** [comment]
I think I'll need to implement an additional local strategy for anonymous in addition to the current local strategy. An example of using multiple strategies for reference: https://github.com/jaredhanson/passport-anonymous/blob/master/examples/basic/app.js
