### ISSUE TITLE
Using slush with marklogic server in HTTPS

### ISSUE THREAD

**Issue by romain-nio** [marklogic/slush-marklogic-node#401]
Hi,

I'm using Marlogic 8 and my cluster is hosted on Amazon Web services (EC2 instance) and behind a load balancer (ELB) with HTTPS enable (https is not enable on marklogic side but on load balancer side).

I want to use Slush to create a tiny reporting web services but I'm wondering about the HTTPS. Is there any known issues about calling marklogic in HTTPS from slush when the HTTPS is not set directly on marklogic ?

Let me know if I'm not clear.

Thanks,
Romain.

**Comment by grtjn** [comment]
We serve demo-cat through httpd that rewrites public https to http against MarkLogic. Slush uses relative paths. I think there should be no issues..

**Comment by romain-nio** [comment]
Thanks for your answer.

I think I was probably not very clear, but we are wondering with my team if slush can natively request a marklogic server which is using HTTPS or do we need to write some specific code to handle that ?

**Comment by grtjn** [comment]
Ah right. You probably want to serve the entire UI from HTTPS too then, but the biggest question here would be what happens in the middle-tier. I think it will fail. In NodeJS you seem to need to use the 'https' package, instead of the 'http' one we are currently using. It could very well just be a matter of replacing `require('http')` with `require('https')`.

Sounds like a useful feature!

**Comment by romain-nio** [comment]
Hi,

Thanks for your answer, very clear answer.

To be honest, I'm sure that this is a mandatory feature. Marklogic is supposed to be a very secured database, so we cannot imagine using it without enabling SSL which is a very basic security standard.

**Comment by grtjn** [comment]
Details on running the entire middle-tier as https server: http://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js

https.request: https://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by grtjn** [comment]
automatic selection between http/https (and the suggestion to use `request`): http://stackoverflow.com/questions/15317902/node-js-automatic-selection-of-http-get-vs-https-get

**Comment by grtjn** [comment]
Re 1.2.0 release. I was cutting down to the bare essential bugs, but hoping a little we can somehow get this in. But there are other things happening in the middle-tier, like the addition of digest support which is close to getting wrapped up. I might need to push it out, but if we do, I align it for 1.2.1. ;-)

Re mandatory: some would argue that the need would be less with DMZ's and such, and that you could bind nodejs and marklogic both to localhost, and have httpd take care of the https handling, but I agree it is important nonetheless, and would add a lot to making slush better prepared for production..

**Comment by grtjn** [comment]
Haven't run a lot of tests yet, but major work should be done..
