### ISSUE TITLE
Admin theme ignores adminLTE.css so the file is missing in git repos

### ISSUE THREAD

**Issue by withjam** [marklogic/slush-marklogic-node#415]
Gitignore is set to ignore styles/*.css to prevent managing generated css files.  However, the admin theme includes adminLTE.css inline and expects it to be in styles/.  Either update .gitignore to allow git to manage styles/adminLTE.css or put that css file somewhere else.

**Comment by grtjn** [comment]
It was removed from gitignore in master branch recently, but not released yet. No need to gitignore css files in that folder. Compiled versions end up elsewhere if i'm right..

**Comment by grtjn** [comment]
Fixed in master..
