### ISSUE TITLE
remove "vkbeautify-wrapper": "*", from bower.json

### ISSUE THREAD

**Issue by devarajanv** [marklogic/slush-marklogic-node#486]
I had to remove "vkbeautify-wrapper": "*", from bower.json inorder to make bower install step after cd <app-name>. removed this line and it worked

**Comment by grtjn** [comment]
Thanks for reporting, we noticed the issue as well ourselves. See also #438.

That ticket also describes a different, and better solution, which has been integrated in latest master branch, and will be included in release 1.3.0.

**Comment by grtjn** [comment]
We are trying to nail down a few last issues, hoping to release 1.3.0 soon. You will get notified automatically when running the slush generator once it has been released..
