### ISSUE TITLE
Generate new (random) secret key for expressSession

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#64]
Every app that is generated, starts with expressSession secret key '1234567890QWERTY'. Generate a real random one, or at least make it more unique (by prepending app-name, timestamp or whatever).

**Comment by grtjn** [comment]
Adding a cookie name, in addition to a unique secret key seems to do the trick:

```
  app.use(expressSession({
    name: 'DEMO-CAT',
    secret: '1234567890DEMO-CAT',
    saveUninitialized: true,
    resave: true
  }));
```

I think we need a gulp task in the slush template that searches 'Sample' and 'sample.' in various files, and replace that with the app name. Anyone up to that?

**Comment by grtjn** [comment]
Afraid this still applies after the big rework..

**Comment by hunterwilliams** [comment]
I'll tackle this today
