### ISSUE TITLE
server.js should honor Content-Disposition and pass-through header

### ISSUE THREAD

**Issue by garyvidal** [marklogic/slush-marklogic-node#67]
When using rest extensions, the server.js should honor a request with Content-Disposition and forward it as a header back to application

To resolve issue 
```js
      //If the file is a download then set the header to passthrough
      if(response.headers["content-disposition"]) {
          res.header("Content-Disposition",response.headers["content-disposition"]);
      }  
```

**Comment by grtjn** [comment]
I think I would vote for a more generic solution in which request and response are passed through entirely, maybe even as-is if possible.

I have successfully used the piping features of the 'request' module. Most essential part would be replacing the existing proxy function with:

```js
  function proxy(req, res) {
    var queryString = req.originalUrl.split('?')[1];
    var mlOptions = {
      method: req.method,
      uri: 'http://' + options.mlHost + ':' + options.mlPort + req.path + (queryString ? '?' + queryString : ''),
      headers: req.headers,
      auth: getAuth(options, req.session)
    };
    try {
      //console.log(req.body + '');
      req.pipe(request(mlOptions)).pipe(res);
    } catch (e) {
      console.log(e);
      res.status(500).send('internal error');
    }
  }
```

**Comment by joemfb** [comment]
I like the proxying approach as well. Much nicer to avoid the low-level request wrangling the current approach requires

**Comment by grtjn** [comment]
I heard there is a new node module that can do proxying: gulp-webserver. I think it is worth looking into..

**Comment by withjam** [comment]
Also check out a module 'http-proxy'.  I have used it in a couple of projects and swapped it in OBI as well.  It's very easy to setup and lets you proxy websockets as well.  It looks like this:

var httpProxy = require('http-proxy');
var mlProxy = httpProxy.createProxyServer( { target: dbUrl } );

  function proxy(req, res) {
    req.headers.Authorization = getAuth(appConfig, req.session);
    mlProxy.web(req,res); // this handles the multipart parsing and everything
  }

**Comment by grtjn** [comment]
So as a replacement for 'http' we have:

- request
- gulp-webserver
- http-proxy

Which makes most sense? I believe request was able to replace http entirely. Does that also apply to gulp-webserver and http-proxy? Can anyone tell?

**Comment by joemfb** [comment]
I used `request` here: https://github.com/joemfb/mlpm-registry/blob/master/server.js#L67 (see the `proxyConfig` and `proxy` functions. I like that flexibility over just using a proxy implementation.

**Comment by grtjn** [comment]
Somewhat related to #31

**Comment by grtjn** [comment]
Bitten by the current proxy code again, when trying to PUT binary to MarkLogic. I'll move forward to using request. @joemfb I'll take a look at your server.js. Do you think it could be (almost) a drop-in replacement?

**Comment by joemfb** [comment]
The latest version has been change pretty drastically, but an early version is mostly drop-in: https://github.com/joemfb/mlpm-registry/blob/36430c3207559a32d89cfc2c7669a116c539ebab/server.js

You'll need to remove the route handler for `/v1/resources/publish`, and replace `application/zip` with the mimetype you'll be using for your binary.

**Comment by grtjn** [comment]
Mimetype? I didn't need that myself. Ah, I guess that was because I got rid of the bodyParser. Didn't see the point of using that.. :)

**Comment by grtjn** [comment]
Just wanted to mention @withjam created an mlProxy component for this. Maybe ask if that would be easy to integrate, and whether it is available as dependency.

**Comment by grtjn** [comment]
Looks like this still applies..

**Comment by grtjn** [comment]
Simplest way out for now is to just copy all headers by default. Looking into that..
