### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#68]
Various important issues have been fixed, but not yet released. Time for a new release.

For those who cannot wait:

`sudo npm install -g git://github.com/marklogic/slush-marklogic-node.git`

**Comment by dmcassel** [comment]
+1

**Comment by grtjn** [comment]
To allow proper support for ML 8, a new Roxy release is necessary. That is work in progress..

**Comment by grtjn** [comment]
For the time being, make sure to select dev branch if picking ML version 8, as Roxy master doesn't accept 8 as server-version value yet..

**Comment by grtjn** [comment]
Fixed: https://github.com/marklogic/slush-marklogic-node/releases/tag/v0.1.2
