### ISSUE TITLE
Add ESRI Map Display in Detail View

### ISSUE THREAD

**Issue by daveegrant** [marklogic/slush-marklogic-node#69]
Begin adding geospatial view of data using ESRI Maps JS API.  This ticket is to add a map display showing the location of a document that contains geospatial data.

**Comment by dmcassel** [comment]
Do we want ESRI as the default mapping approach?

**Comment by daveegrant** [comment]
After discussions withe Dave Cassel, we will include the ESRI Maps integration as an optional inclusion for the generator.  The default will be to NOT include the ESRI Maps integration code.
