### ISSUE TITLE
Module 'gd.ui.jsonexplorer' is not available

### ISSUE THREAD

**Issue by dmcassel** [marklogic/slush-marklogic-node#71]
Got the latest from this repo, generated a project, updated Roxy properties for MarkLogic 8 (server-version, url-rewriter). Bootstrapped, deployed, gulp, gulp server. Tried to load the app's home page and got this error: 

    Uncaught Error: [$injector:modulerr] Failed to instantiate module sample due to:
    Error: [$injector:modulerr] Failed to instantiate module gd.ui.jsonexplorer due to:
    Error: [$injector:nomod] Module 'gd.ui.jsonexplorer' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

In the generated app, ui/app/app.js has a reference to gd.ui.jsonexplorer. bower.json has 

    "ng-json-explorer": "*",

"npm install" and "bower install" have both been run.

**Comment by grtjn** [comment]
I think Dave Grant noticed this too last week. Seemed to be caused by changes in jsonexplorer.


Sent from Samsung Mobile
