### ISSUE TITLE
Prompt user for MarkLogic version

### ISSUE THREAD

**Issue by dmcassel** [marklogic/slush-marklogic-node#73]
The slush template assumes the use of MarkLogic 7.

**Comment by grtjn** [comment]
Ah yes, looks like it is hardcoded indeed. I'd say, maybe suppress most of the params. The `ml new` prompts for input itself..

**Comment by grtjn** [comment]
Hmm, the spawn hides user prompts from the ml script itself. And I was trying to add version 8, but Roxy master branch doesn't accept it yet. I'll reach out to Paxton to see if we can get a new Roxy release out..

**Comment by grtjn** [comment]
See https://github.com/marklogic/roxy/issues/376
