### ISSUE TITLE
Detail view is not showing data

### ISSUE THREAD

**Issue by daveegrant** [marklogic/slush-marklogic-node#79]
After generating an app using slush, the detail view of a search result is not showing the data.  The new version of the json-explorer directive should use `<data>` as the attribute to identify the data rather than `<json-data>`.

**Comment by grtjn** [comment]
One reason for this to keep turning up is that we don't have a version-specific dependency on json-explorer in bower.json. Last time I looked into that, I failed to change that. Maybe you have time to take a look at that as well?

**Comment by daveegrant** [comment]
Added dependency on commit # for json-explorer since version details are not updated on release.

**Comment by grtjn** [comment]
Fixed
