### ISSUE TITLE
Need help with updating the JSON document

### ISSUE THREAD

**Issue by theyinyanguy** [marklogic/slush-marklogic-node#83]
Hi,
I am using this wonderful framework to create a basic search application and I tried extending the details part of the application to demonstrate the update. I am not able to the get the code the right for the update submit function. I think I am missing on something very basic. I would really appreciate quick tips as I am running out of time. Following is the code for the file "detail-ctrl.js".

    (function () {
      'use strict';

      angular.module('sample.detail')
        .controller('DetailCtrl', ['$scope', 'MLRest', '$routeParams', function ($scope, mlRest, $routeParams) {
          var uri = $routeParams.uri;
          var model = {
            // your model stuff here
            detail: {},
            adid: 0,
            city: '',
            desc: '',
            latitude: 0,
            link: '',
            logitude: 0,
            postedon: '',
            price: '',
            suburb: '',
            title: '',
            uri: ''
          };

          mlRest.getDocument(uri, { format: 'json' }).then(function(response) {
            model.detail = response.data;
            model.adid = response.data.adid;
            model.city = response.data.city;
            model.desc = response.data.desc;
            model.latitude = response.data.latitude;
            model.link = response.data.link;
            model.longitude = response.data.longitude;
            model.postedon = response.data.postedon;
            model.price = response.data.price;
            model.suburb = response.data.suburb;
            model.title = response.data.title;
            model.uri = $routeParams.uri;
          });

          angular.extend($scope, {
            model: model,
            // 
            submit: function() {
              //mlRest.updateDocument($scope.model,$scope.model.uri)
              mlRest.updateDocument($scope.model, {
                //format: 'json',
                //directory: '/car/',
                //extension: '.json'
                // TODO: add read/update permissions here like this:
                // 'perm:sample-role': 'read',
                // 'perm:sample-role': 'update'
              }).then(function(response) {
                //win.location.href = '/detail?uri=' + response.headers('location').replace(/(.*\?uri=)/, '');
                win.location.href = '?uri=' + model.uri;
              });
            }
            //
          });
        }]);
    }());

I have modified the code to display the data in the text box(from the json-explorer to facilitate the updates). With this code I am getting following error.

TypeError: Cannot read property 'match' of undefined
    at /Users/pmakwana/MyWork/carsearch/server.js:176:20
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)
    at /Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:261:10)
    at urlencodedParser (/Users/pmakwana/MyWork/carsearch/node_modules/body-parser/lib/types/urlencoded.js:77:44)
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)

Any tips on resolving the error would be really helpful. Also if there is any sample update application which use slush marklogic-node would be helpful.
Thanks in advance.
regards,
Puneet

**Comment by joemfb** [comment]
The error in server.js is from trying to match a regex to an undefined property (in this case, the expected URI param).

To update an existing document, you need to pass it's URI as an object property:

     mlRest.updateDocument($scope.model, { uri: uri })

This will work fine with the existing server.js. It will also work to create a new document, at the specified URI.

However, you'll need to modify server.js to be able to create a new document without specifying a URI, but specifying the directory and extension. In the express handler for REST API PUT requests (https://github.com/marklogic/slush-marklogic-node/blob/master/app/templates/server.js#L171), try removing anything that depends on the presence of the URI param.

For instance, the following should work for you (but removes the access control surrounding user profile documents)

    app.put('/v1*', function(req, res) {
      // For PUT requests, require authentication
      if (req.session.user === undefined) {
        res.send(401, 'Unauthorized');
      } else {
        proxy(req, res);
      }
    });

This should work, and preservers user profile access control:

    app.put('/v1*', function(req, res) {
      // For PUT requests, require authentication
      if (req.session.user === undefined) {
        res.send(401, 'Unauthorized');
      } else if (req.path === '/v1/documents' &&
        req.query.uri &&
        req.query.uri.match('/users/') &&
        req.query.uri.match(new RegExp('/users/[^(' + req.session.user.name + ')]+.json'))) {
        // The user is try to PUT to a profile document other than his/her own. Not allowed.
        res.send(403, 'Forbidden');
      } else {
        if (req.path === '/v1/documents' && req.query.uri && req.query.uri.match('/users/')) {
          // TODO: The user is updating the profile. Update the session info.
        }
        proxy(req, res);
      }
    });

**Comment by theyinyanguy** [comment]
Hi Joe,
Thank you for your response. IN my sample application, I am also using createDocument. Would the change in server.js impact the existing create functionality?
Looking forward to hear from you.
regards,
Puneet

**Comment by joemfb** [comment]
`mlRest.createDocument()` makes a POST request to /v1/documents, so it wouldn't be impacted by this change.

In general server.js is a REST API proxy and session store. It's use of the `express` middleware framework makes it very easy to customize, and that customization is encouraged!

**Comment by theyinyanguy** [comment]
Thank You Joe.
Now I have following code in the update button
mlRest.updateDocument($scope.model,{uri: $scope.model.uri})}
and the error is 

TypeError: Cannot read property 'match' of undefined
    at /Users/pmakwana/MyWork/carsearch/server.js:176:20
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)
    at /Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:321:12)
    at next (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/index.js:261:10)
    at urlencodedParser (/Users/pmakwana/MyWork/carsearch/node_modules/body-parser/lib/types/urlencoded.js:77:44)
    at Layer.handle [as handle_request] (/Users/pmakwana/MyWork/carsearch/node_modules/express/lib/router/layer.js:82:5)

It seems like the same error. And I also see an error in the web console "HTTP/1.1 500 Internal Server Error"
what could be the issue here?
regards,
Puneet

**Comment by theyinyanguy** [comment]
Just realized I my uri variable was undefined.
Can you advice which variable would have uri information to pass to mlRest.updateDocument()?
$routeParams.uri is also empty.
regards,
Puneet

**Comment by theyinyanguy** [comment]
Thanks Joe. I figured it out. I created another variable and was able to pass it. Thank You for very much for your support. I really appreciate your support on the weekend.
Regards,
Puneet
