### ISSUE TITLE
Add default robots.txt's

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#85]
In both ui/app/ and src/ containing:

User-agent: *
Disallow: /

**Comment by hunterwilliams** [comment]
I understand ui/app/ but is src/ mounted as to be accessible by any robots? I'd assume they need to login

**Comment by grtjn** [comment]
Depends on the routes in the middle-tier. If a call for robots.txt does get forwarded to MarkLogic, then MarkLogic will look for such a file in the modules db. Better safe than sorrow. And it won't do harm to anyone either.

Otherwise good thinking, only /v1/* get forwarded to MarkLogic by default..
