### ISSUE TITLE
Use extspell.xqy

### ISSUE THREAD

**Issue by theyinyanguy** [marklogic/slush-marklogic-node#86]
I noticed dictionary-large.xml in the data folder and extspell.xqy in rest api ext directory.
is this for search suggestions in query text?
is this configured to work by default, I was not able to use it?
are there any steps for configuration?

**Comment by grtjn** [comment]
extspell is a custom extension that generates a list of words based on a given (search) string, and derived from a dictionary (dictionary-large.xml in this example). It is not connected in the UI out of the box, but could be useful for providing alternative search terms when no or limited search results were found. A bit like the 'Did you mean ..?' from Google.

To leverage it you would execute the search as normally, inspect the returned total count, and optionally respond by making a call to extspell, and show the returned suggestions somewhere near the search bar. You should be able to call the extension with something like this:

```js
          mlRest.callExtension('extspell',
            {
              method: 'POST',
              data: '',
              params: {
                'rs:pqtxt': 'myterm'
              }
            }
          ).then(
            function(result) {
              model.spellSuggesions = result.data;
            }
          );
```

**Comment by theyinyanguy** [comment]
Thanks Geert!
This would be useful.
