### ISSUE TITLE
Add geospatial component

### ISSUE THREAD

**Issue by dmcassel** [marklogic/slush-marklogic-node#9]
To make it easy to set up geospatial search, include components in the generator for doing so.

**Comment by daveegrant** [comment]
Submitted PR with initial integration Google Maps updates.  Tested on ML 7.  Should work fine in ML 8 if data is stored as XML but will not work if stored as native JSON.  Will open new ticket for handling native JSON.

**Comment by grtjn** [comment]
Good chance it 'just works' with native JSON as well..

**Comment by grtjn** [comment]
I started new component https://github.com/grtjn/ml-google-maps-ng that is supposed to merge all maps related things, including work from Dave G, Matt P, and me..

**Comment by grtjn** [comment]
How much geospatial support should be in the vanilla generated app? Does the ESRI option still make sense, especially since it only shows a map on the details page?

**Comment by hunterwilliams** [comment]
I assume don't include maps unless specifically asked for. So should something be changed from the current situation?

**Comment by grtjn** [comment]
Moving this to milestone 0.2.1. There is ESRI support for the detail page, and the ml-google-maps-ng can fill the need for geo searching for the moment.

Still a good question though. It makes sense to include frequently used components into the slush generator, to make it easier to get started.

**Comment by grtjn** [comment]
I am considering closing this ticket. Since newer slush template we moved away from having such components inside the slush generator itself. We have cookbook recipes (#167) for adding separate components like ml-google-maps-ng and such, and Dave G is working on one for similar functionality using ESRI.

Votes?

**Comment by jenbreese** [comment]
I vote we close it as a no longer relevant ticket.

**Comment by grtjn** [comment]
@daveegrant Did you publish your work on the new ESRI component yet?

**Comment by grtjn** [comment]
There is a separate ticket for the ESRI component: #233, closing this one..
