### ISSUE TITLE
default app user cannot use the app

### ISSUE THREAD

**Issue by hugokoopmans** [marklogic/slush-marklogic-node#95]
Hi,

I want to set up the default app user from the template. It gets created all right and also has the app-role.
So I can login to the app but it does not return search results.

I added additional roles like rest-extension-user,rest-reader, search-internal, slush-dikw-node-role but no luck. Looked at previligenges and collections but that seems not relevant. Searched in Roxy on [role-based-security](https://github.com/marklogic/roxy/wiki/Security) no real pointers.

Looked at ml-config.xml but no pointers there on what to add/change.
What am I missing to get the default app user to work? (or even better a blueprint for an additional named user)

**Comment by grtjn** [comment]
Verify that the user is actually allowed to make REST api calls by checking the browser console, or calling /v1/search with the browser directly. Also make sure to hand out appropriate document permissions for the documents you are uploading..

**Comment by hugokoopmans** [comment]
Verified I can get to REST API with user ... check
Verified I can query REST search endpoint ... check no results
Indeed we have uploaded docs as admin and we would like to upload user different from the app-user. 
Can you show me how to change permissions on a document (or collection) for a specific user preferable from roxy... thx

**Comment by grtjn** [comment]
You would normally apply doc permissions at upload. If you use Roxy to `deploy content` from the data/ directory, that will get read/update permission for app-role. If you use MLCP (through Roxy or not) you can explicitly specify output_permissions. If you use custom code to upload content, then use a user that has default permissions according what you want to be applied to any doc inserted with that user.

**Comment by grtjn** [comment]
Can we close this?

**Comment by hugokoopmans** [comment]
Using mlcp with -output_permissions works!

example:
 mlcp.sh import -host localhost -port 8140 -username aaa -password xyz -input_file_path /home/ashraf/data/sample  -mode local -output_uri_replace       "\".*/data/sample,''\"" -output_uri_prefix incoming/linkedin/ -output_collections incoming,incoming/linkedin -output_permissions slush-dikw-node-role,read
